version: '3.9'

services:
  importer:
    depends_on:
      - mongo
  api:
    build: ./api
    ports:
      - 3001:3001
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
      - PORT=3001
    depends_on:
      - mongo

  app:
    build: ./app
    container_name: react_app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./pastries.json:/tmp/pastries.json
      - ./importscript.sh:/importscript.sh
    
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password
    #  MONGO_INITDB_DATABASE: yams_db
    #volumes:
    #  - ./data:/data/db
    #  - ./pastries.json:/tmp/pastries.json
    #  - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro


    
      
    #volumes:
    #  - ./pastries.json:/usr/src/pastries.json
    #  - docker_mongo_data:/data/db